language: julia

# tests also work on 1.3.x but the build image seems to be broken for those
# versions or there is some bug in Pkg. Thus, using 1.4 for now.
julia:
  - 1.4

os:
  - linux

codecov: true
